package com.ldp;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89

This class finds sum of all even fibonacci members below specifies limit.
 */

public class EvenFibonacci {
    private int highLimit;
    private int firstNumber = 1;
    private int secondNumber = 2;

    public EvenFibonacci(int highLimit) {
        this.highLimit = highLimit;
    }

    public long getSumOfEvenMembers() {
        long sum = 2; //second number is even

        int thirdNumber = 0;
        while (thirdNumber < highLimit) {

            thirdNumber = firstNumber + secondNumber;
            if (thirdNumber % 2 == 0) sum += thirdNumber;

            firstNumber = secondNumber;
            secondNumber = thirdNumber;
        }

        return sum;
    }
}


